# This workflow is manually triggered (workflow_dispatch).
# It builds and pushes the Docker images to ECR.

name: Continuous Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "testnet1_staging"
        type: choice
        options:
          # Env that corresponds to the releases/0.2.0 branch
          - testnet1_staging
          # Env that corresponds to the main branch
          - development

env:
  CI: false
  COMMIT: ${{ github.sha }}

permissions:
  contents: read
  pull-requests: read

jobs:
  build-and-push:
    permissions:
      id-token: write
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || (github.ref == 'refs/heads/main' && 'development') }}
    strategy:
      matrix:
        # The names of the programs must match the names of the directories that we
        # are building the Docker images from.
        # The directories `bin` and `docker` must contain the subdirectories in the
        # matrix below.
        program: [prover-client]
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Configure AWS ECR Details
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: ${{ secrets.AWS_ECR_ROLE }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2
        with:
          mask-password: "true"

      - name: Set up Clang
        uses: egor-tensin/setup-clang@23bc15cd4207e45f1566447deb48f4ff3ef932cb # v2.3
        with:
          version: latest
          platform: x64

      - name: Install SP1 Toolchain
        run: |
          curl -fsSL --proto '=https' --tlsv1.2 https://sp1.succinct.xyz | bash && ~/.sp1/bin/sp1up
          export PATH=~/.sp1/bin:$PATH
          cargo prove --version

      - name: Install protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        # build and push the Docker image for every program
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_PREFIX: ${{ github.ref == 'refs/heads/main' && vars.ECR_REPOSITORY_PREFIX_MAIN || vars.ECR_REPOSITORY_PREFIX }}
        run: |
          SHORT_TAG="${COMMIT//[^a-zA-Z0-9._-]/}"
          SHORT_TAG="${SHORT_TAG:0:7}"
          PROGRAM="${{ matrix.program }}"

          echo "Building and pushing \"$PROGRAM\" image with tag \"$SHORT_TAG\""

          DOCKERFILE_PATH="docker/${PROGRAM}/Dockerfile"
          ECR_REPOSITORY="${ECR_REPOSITORY_PREFIX}/${PROGRAM}"

          if [ "$PROGRAM" == "prover-client" ]; then
            # Build prover with sp1 features
            docker build \
              --build-arg PROVER_FEATURES="sp1" \
              -t "${ECR_REGISTRY}/${ECR_REPOSITORY}:${SHORT_TAG}" \
              -f "${DOCKERFILE_PATH}" .
            # TODO(STR-1527): build (and push) a docker image for prover in native mode as well.
          else
            docker build -t "${ECR_REGISTRY}/${ECR_REPOSITORY}:${SHORT_TAG}" \
              -f "${DOCKERFILE_PATH}" .
          fi

          # Push the image to ECR
          docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}:${SHORT_TAG}"
