name: Docs

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  extract-rust-version:
    name: Extract Rust toolchain version
    runs-on: ubuntu-latest
    outputs:
      rust-version: ${{ steps.extract.outputs.rust-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Extract Rust toolchain version
        id: extract
        uses: ./.github/actions/extract-rust-version # zizmor: ignore[unpinned-uses]

  docs:
    name: Generate docs
    runs-on: ubuntu-latest
    needs: extract-rust-version
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Rust
        env:
          RUST_NIGHTLY: ${{ needs.extract-rust-version.outputs.rust-version }}
        run: |
          rustup toolchain install "$RUST_NIGHTLY" --profile minimal
          rustup default "$RUST_NIGHTLY"

      - name: Install protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          cache-on-failure: true

      - name: Install SP1 core runner override
        uses: ./.github/actions/sp1-core-runner-override # zizmor: ignore[unpinned-uses]

      - name: Check docs leaving the dependencies out
        env:
          RUSTDOCFLAGS: --show-type-layout --enable-index-page -Zunstable-options -A rustdoc::private-doc-tests -D warnings
        run: cargo doc --workspace --all-features --no-deps
